const authStyles = {
  page: {
    minHeight: '100vh',
    display: 'flex',
    background: '#F8F9FB',
  },
  brand: {
    flex: '0 0 44%',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'flex-start',
    padding: '48px 40px 48px 28px',
    background: 'linear-gradient(145deg, #1E3A8A 0%, #3B82F6 55%, #60A5FA 100%)',
    color: '#fff',
    boxSizing: 'border-box',
  },
  brandLogo: {
    fontSize: 28,
    fontWeight: 700,
    marginBottom: 16,
  },
  brandTitle: {
    fontSize: 32,
    fontWeight: 700,
    lineHeight: 1.2,
    margin: '0 0 12px',
    maxWidth: 360,
  },
  brandText: {
    fontSize: 16,
    lineHeight: 1.6,
    opacity: 0.9,
    maxWidth: 400,
    margin: 0,
  },
  panel: {
    flex: 1,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'flex-start',
    padding: '24px 48px 24px 32px',
    boxSizing: 'border-box',
  },
  card: {
    width: '100%',
    maxWidth: 420,
    marginLeft: 8,
    background: '#fff',
    borderRadius: 16,
    border: '1px solid #E2E8F0',
    padding: 32,
    boxShadow: '0 8px 32px rgba(15, 23, 42, 0.08)',
  },
  mobileLogo: {
    display: 'none',
    fontSize: 22,
    fontWeight: 700,
    color: '#0F172A',
    marginBottom: 20,
  },
  tabs: {
    display: 'flex',
    gap: 4,
    padding: 4,
    background: '#F1F5F9',
    borderRadius: 10,
    marginBottom: 28,
  },
  tab: {
    flex: 1,
    padding: '10px 16px',
    fontSize: 14,
    fontWeight: 500,
    border: 'none',
    borderRadius: 8,
    cursor: 'pointer',
    background: 'transparent',
    color: '#64748B',
    transition: 'all 0.15s ease',
  },
  tabActive: {
    background: '#fff',
    color: '#0F172A',
    fontWeight: 600,
    boxShadow: '0 1px 3px rgba(15, 23, 42, 0.08)',
  },
  title: {
    margin: '0 0 6px',
    fontSize: 22,
    fontWeight: 700,
    color: '#0F172A',
  },
  subtitle: {
    margin: '0 0 24px',
    fontSize: 14,
    color: '#64748B',
  },
  row: {
    display: 'flex',
    gap: 12,
  },
  field: {
    flex: 1,
    marginBottom: 16,
  },
  label: {
    display: 'block',
    fontSize: 13,
    fontWeight: 500,
    color: '#334155',
    marginBottom: 6,
  },
  input: {
    width: '100%',
    padding: '10px 12px',
    fontSize: 14,
    border: '1px solid #E2E8F0',
    borderRadius: 8,
    boxSizing: 'border-box',
    outline: 'none',
  },
  btn: {
    width: '100%',
    padding: '12px 16px',
    fontSize: 14,
    fontWeight: 600,
    color: '#fff',
    background: '#3B82F6',
    border: 'none',
    borderRadius: 8,
    cursor: 'pointer',
    marginTop: 8,
  },
  btnDisabled: {
    opacity: 0.7,
    cursor: 'not-allowed',
  },
  error: {
    margin: '0 0 16px',
    fontSize: 13,
    color: '#DC2626',
    background: '#FEF2F2',
    padding: '10px 12px',
    borderRadius: 8,
    lineHeight: 1.4,
  },
  hint: {
    margin: '16px 0 0',
    fontSize: 13,
    color: '#64748B',
    textAlign: 'center',
  },
  link: {
    color: '#3B82F6',
    fontWeight: 500,
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    padding: 0,
    fontSize: 'inherit',
  },
};

export default authStyles;