const styles = {
  app: {
    minHeight: '100vh',
    display: 'flex',
    background: '#F8F9FB',
  },
  sidebar: {
    width: 260,
    display: 'flex',
    flexDirection: 'column',
    background: '#fff',
    borderRight: '1px solid #E2E8F0',
    padding: '24px 16px',
    boxSizing: 'border-box',
  },
  logo: {
    fontSize: 20,
    fontWeight: 700,
    color: '#0F172A',
    marginBottom: 32,
    display: 'flex',
    alignItems: 'center',
    gap: 8,
  },
  logoDot: {
    color: '#3B82F6',
    fontSize: 24,
  },
  nav: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    gap: 4,
  },
  navItem: {
    width: '100%',
    padding: '10px 12px',
    fontSize: 14,
    fontWeight: 400,
    color: '#64748B',
    background: 'transparent',
    border: 'none',
    borderRadius: 8,
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    gap: 10,
    textAlign: 'left',
    transition: 'all 0.15s ease',
  },
  sidebarBottom: {
    paddingTop: 16,
    borderTop: '1px solid #E2E8F0',
  },
  userRow: {
    display: 'flex',
    alignItems: 'center',
    gap: 12,
  },
  userAvatar: {
    width: 36,
    height: 36,
    borderRadius: '50%',
    background: '#3B82F6',
    color: '#fff',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: 14,
    fontWeight: 600,
  },
  userName: {
    margin: 0,
    fontSize: 14,
    fontWeight: 600,
    color: '#0F172A',
  },
  userRole: {
    margin: 0,
    fontSize: 12,
    color: '#64748B',
  },
  main: {
    flex: 1,
    overflow: 'auto',
  },
};

export default styles;
