const styles = {
  page: {
    fontFamily: "'DM Sans', 'Segoe UI', sans-serif",
    background: '#F8F9FB',
    minHeight: '100vh',
    padding: '32px',
    boxSizing: 'border-box',
  },
  header: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 20,
  },
  heading: { fontSize: 26, fontWeight: 600, color: '#0F172A', margin: 0 },
  subheading: { fontSize: 13, color: '#94A3B8', margin: '4px 10px' },
  btnPrimary: {
    padding: '8px 18px',
    fontSize: 13,
    fontWeight: 500,
    background: '#3B82F6',
    color: '#fff',
    border: 'none',
    borderRadius: 8,
    cursor: 'pointer',
  },
  btnSecondary: {
    padding: '8px 18px',
    fontSize: 13,
    fontWeight: 600,
    background: '#F1F5F9',
    color: '#0F172A',
    border: '1px solid #E2E8F0',
    borderRadius: 10,
    cursor: 'pointer',
    transition: 'transform 0.15s ease, box-shadow 0.15s ease, background 0.15s ease, border-color 0.15s ease',
    boxShadow: '0 1px 2px rgba(0,0,0,0.04)',
  },
  summaryRow: {
    display: 'flex',
    gap: 24,
    marginBottom: 20,
    background: '#fff',
    borderRadius: 10,
    padding: '12px 20px',
    boxShadow: '0 1px 3px rgba(0,0,0,0.06)',
  },
  summaryItem: { display: 'flex', alignItems: 'center', gap: 8 },
  summaryDot: { width: 8, height: 8, borderRadius: '50%' },
  summaryLabel: { fontSize: 12, color: '#64748B' },
  summaryVal: { fontSize: 13, fontWeight: 600 },
  board: {
    display: 'grid',
    gridTemplateColumns: 'repeat(4, 1fr)',
    gap: 14,
    alignItems: 'start',
  },
  column: {
    borderRadius: 12,
    padding: 14,
    transition: 'background 0.15s',
  },
  colHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  colLeft: { display: 'flex', alignItems: 'center', gap: 8 },
  colTitle: { fontSize: 13, fontWeight: 600, color: '#0F172A' },
  colCount: {
    fontSize: 11,
    fontWeight: 600,
    padding: '2px 8px',
    borderRadius: 99,
  },
  colTotal: { fontSize: 12, fontWeight: 600, color: '#64748B' },
  cardsList: { display: 'flex', flexDirection: 'column', gap: 8 },
  loadMoreBtn: {
    width: '100%',
    marginTop: 4,
    padding: '8px 12px',
    fontSize: 12,
    fontWeight: 500,
    color: '#475569',
    background: '#fff',
    border: '1px dashed #CBD5E1',
    borderRadius: 8,
    cursor: 'pointer',
  },
  dealCard: {
    background: '#fff',
    borderRadius: 10,
    padding: '12px 14px',
    border: '1px solid #F1F5F9',
    boxShadow: '0 1px 2px rgba(0,0,0,0.04)',
    cursor: 'grab',
    transition: 'box-shadow 0.15s, transform 0.15s',
  },
  dealName: {
    fontSize: 13,
    fontWeight: 500,
    color: '#0F172A',
    margin: '0 0 15px',
  },
  managerName: { fontSize: 12, color: '#94A3B8', margin: '0 0 6px' },
  clientName: {
    fontSize: 12,
    color: '#94A3B8',
    margin: '0 0 10px 10px',
    display: 'block',
  },
  dealFooter: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  dealAmount: { fontSize: 14, fontWeight: 700 },
  dealDate: { fontSize: 11, color: '#CBD5E1' },
  clientName: { 
    fontSize: 12, 
    color: '#94A3B8', 
    margin: '0 0 0 180px',
    marginTop: -17,
    marginBottom: 10,
    display: 'flex',
  },
  dropZone: {
    border: '2px dashed',
    borderRadius: 10,
    padding: '14px',
    textAlign: 'center',
    fontSize: 12,
    fontWeight: 500,
  },
  modalOverlay: {
    position: 'fixed',
    inset: 0,
    background: 'rgba(0,0,0,0.3)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 100,
  },
  modal: {
    background: '#fff',
    borderRadius: 14,
    padding: '28px 28px 24px',
    width: 380,
    boxShadow: '0 20px 60px rgba(0,0,0,0.15)',
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: 600,
    color: '#0F172A',
    margin: '0 0 20px',
  },
  formGroup: { marginBottom: 14 },
  label: {
    display: 'block',
    fontSize: 12,
    fontWeight: 500,
    color: '#475569',
    marginBottom: 5,
  },
  input: {
    width: '100%',
    padding: '8px 12px',
    fontSize: 13,
    border: '1px solid #E2E8F0',
    borderRadius: 8,
    background: '#fff',
    color: '#0F172A',
    outline: 'none',
    boxSizing: 'border-box',
  },
  modalActions: {
    display: 'flex',
    justifyContent: 'flex-end',
    gap: 8,
    marginTop: 20,
  },
  breadcrumb: {
    display: 'flex',
    alignItems: 'center',
    gap: 6,
    marginBottom: 20,
  },
  breadSep: { fontSize: 13, color: '#CBD5E1' },
  breadCurrent: { fontSize: 13, color: '#94A3B8' },
};

export default styles;
