const styles = {
  page: {
    fontFamily: "'DM Sans', 'Segoe UI', sans-serif",
    background: "#F8F9FB",
    minHeight: "100vh",
    padding: "32px",
    boxSizing: "border-box",
  },
  header: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: 24,
  },
  heading: { fontSize: 26, fontWeight: 600, color: "#0F172A", margin: 0 },
  subheading: { fontSize: 13, color: "#94A3B8", margin: "4px 0 0" },
  layout: {
    display: "flex",
    gap: 24,
    alignItems: "flex-start",
  },
  profileCard: {
    background: "#fff",
    borderRadius: 12,
    padding: 32,
    boxShadow: "0 1px 3px rgba(0,0,0,0.06)",
    border: "1px solid #F1F5F9",
    minWidth: 280,
    textAlign: "center",
  },
  avatarLg: {
    width: 80,
    height: 80,
    borderRadius: "50%",
    background: "#3B82F6",
    color: "#fff",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 28,
    fontWeight: 600,
    margin: "0 auto 16px",
  },
  userName: {
    fontSize: 20,
    fontWeight: 600,
    color: "#0F172A",
    margin: "0 0 4px",
  },
  userRole: {
    fontSize: 14,
    color: "#64748B",
    margin: "0 0 16px",
  },
  statusBadge: {
    display: "flex",
    justifyContent: "center",
  },
  badge: {
    display: "inline-block",
    fontSize: 12,
    padding: "4px 12px",
    borderRadius: 99,
    fontWeight: 600,
  },
  infoBlock: {
    background: "#fff",
    borderRadius: 12,
    padding: 24,
    boxShadow: "0 1px 3px rgba(0,0,0,0.06)",
    border: "1px solid #F1F5F9",
    flex: 1,
    minWidth: 0,
  },
  blockTitle: {
    fontSize: 14,
    fontWeight: 600,
    color: "#0F172A",
    margin: "0 0 16px",
  },
  infoRow: {
    display: "flex",
    justifyContent: "space-between",
    padding: "12px 0",
    borderBottom: "1px solid #F1F5F9",
  },
  infoKey: {
    fontSize: 13,
    color: "#64748B",
    fontWeight: 500,
  },
  infoVal: {
    fontSize: 13,
    color: "#0F172A",
    fontWeight: 500,
  },
};

export default styles;
