const styles = {
  page: {
    fontFamily: "'DM Sans', 'Segoe UI', sans-serif",
    background: "#F8F9FB",
    minHeight: "100vh",
    padding: "32px",
    boxSizing: "border-box",
  },
  breadcrumb: { display: "flex", alignItems: "center", gap: 6, marginBottom: 20 },
  breadLink: { fontSize: 13, color: "#3B82F6", cursor: "pointer" },
  breadSep: { fontSize: 13, color: "#CBD5E1" },
  breadCurrent: { fontSize: 13, color: "#94A3B8" },
  layout: { display: "grid", gridTemplateColumns: "280px 1fr", gap: 16, alignItems: "start" },
  leftPanel: { display: "flex", flexDirection: "column", gap: 12 },
  profileCard: {
    background: "#fff", borderRadius: 12, padding: "24px 20px",
    textAlign: "center", boxShadow: "0 1px 3px rgba(0,0,0,0.06)",
  },
  avatarLg: {
    width: 64, height: 64, borderRadius: "50%",
    background: "#DBEAFE", color: "#2563EB",
    display: "flex", alignItems: "center", justifyContent: "center",
    fontSize: 22, fontWeight: 700, margin: "0 auto 12px",
  },
  clientName: { fontSize: 17, fontWeight: 600, color: "#0F172A", margin: "0 0 4px" },
  clientPos: { fontSize: 12, color: "#94A3B8", margin: "0 0 12px" },
  tagsRow: { display: "flex", gap: 6, justifyContent: "center", flexWrap: "wrap", marginBottom: 14 },
  tag: {
    fontSize: 11, padding: "3px 10px", borderRadius: 99,
    background: "#DCFCE7", color: "#16A34A", fontWeight: 600,
  },
  actionBtns: { display: "flex", gap: 8 },
  actionBtn: {
    flex: 1, padding: "7px 0", fontSize: 12, fontWeight: 500,
    background: "#F8F9FB", color: "#475569", border: "1px solid #E2E8F0",
    borderRadius: 8, cursor: "pointer",
  },
  infoBlock: {
    background: "#fff", borderRadius: 12, padding: "16px 18px",
    boxShadow: "0 1px 3px rgba(0,0,0,0.06)",
  },
  blockTitle: { fontSize: 12, fontWeight: 600, color: "#94A3B8", textTransform: "uppercase", letterSpacing: "0.05em", margin: "0 0 10px" },
  infoRow: {
    display: "flex", justifyContent: "space-between", alignItems: "center",
    padding: "7px 0", borderBottom: "1px solid #F1F5F9",
  },
  infoKey: { fontSize: 12, color: "#94A3B8" },
  infoVal: { fontSize: 12, fontWeight: 500 },
  statsRow: {
    background: "#fff", borderRadius: 12, padding: "16px 20px",
    display: "flex", alignItems: "center", justifyContent: "space-around",
    boxShadow: "0 1px 3px rgba(0,0,0,0.06)",
  },
  statItem: { textAlign: "center" },
  statVal: { fontSize: 20, fontWeight: 700, color: "#0F172A", margin: 0 },
  statLabel: { fontSize: 11, color: "#94A3B8", margin: "3px 0 0" },
  statDivider: { width: 1, height: 36, background: "#F1F5F9" },
  rightPanel: {
    background: "#fff", borderRadius: 12,
    boxShadow: "0 1px 3px rgba(0,0,0,0.06)", overflow: "hidden",
  },
  tabs: {
    display: "flex", borderBottom: "1px solid #F1F5F9", padding: "0 20px",
  },
  tabBtn: {
    padding: "14px 16px", fontSize: 13, background: "none",
    border: "none", borderBottom: "2px solid transparent",
    cursor: "pointer", transition: "all 0.15s",
  },
  tabContent: { padding: "20px 24px" },
  timelineItem: { display: "flex", gap: 12, marginBottom: 18 },
  timelineIcon: {
    width: 32, height: 32, borderRadius: "50%", flexShrink: 0,
    display: "flex", alignItems: "center", justifyContent: "center",
    marginTop: 2,
  },
  timelineBody: { flex: 1, paddingBottom: 18, borderBottom: "1px solid #F8F9FB" },
  timelineText: { fontSize: 13, color: "#334155", margin: "0 0 4px", lineHeight: 1.5 },
  timelineTime: { fontSize: 11, color: "#94A3B8", margin: 0 },
  dealRow: {
    display: "flex", justifyContent: "space-between", alignItems: "center",
    padding: "14px 0", borderBottom: "1px solid #F8F9FB",
  },
  dealName: { fontSize: 13, fontWeight: 500, color: "#0F172A", margin: "0 0 3px" },
  dealStage: { fontSize: 12, color: "#94A3B8", margin: 0 },
  dealRight: { textAlign: "right" },
  dealAmount: { fontSize: 14, fontWeight: 700, color: "#3B82F6", margin: "0 0 4px" },
  dealBadge: {
    fontSize: 11, padding: "2px 8px", borderRadius: 99, fontWeight: 500,
  },
  addDealBtn: {
    marginTop: 14, padding: "8px 16px", fontSize: 13, fontWeight: 500,
    background: "#F1F5F9", color: "#475569", border: "none",
    borderRadius: 8, cursor: "pointer", width: "100%",
  },
  noteArea: {
    width: "100%", minHeight: 140, padding: "12px 14px", fontSize: 13,
    border: "1px solid #E2E8F0", borderRadius: 8, resize: "vertical",
    color: "#334155", lineHeight: 1.6, boxSizing: "border-box", outline: "none",
  },
  saveBtn: {
    marginTop: 10, padding: "8px 20px", fontSize: 13, fontWeight: 500,
    background: "#3B82F6", color: "#fff", border: "none",
    borderRadius: 8, cursor: "pointer",
  },
  dealsTabHeader: {
    display: "flex",
    justifyContent: "flex-end",
    marginBottom: 12,
  },
  btnPrimary: {
    padding: "8px 16px",
    fontSize: 13,
    fontWeight: 600,
    color: "#fff",
    background: "#3B82F6",
    border: "none",
    borderRadius: 8,
    cursor: "pointer",
  },
  btnSecondary: {
    padding: "8px 16px",
    fontSize: 13,
    fontWeight: 500,
    color: "#64748B",
    background: "#fff",
    border: "1px solid #E2E8F0",
    borderRadius: 8,
    cursor: "pointer",
  },
  overlay: {
    position: "fixed",
    inset: 0,
    background: "rgba(15, 23, 42, 0.4)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 1000,
    padding: 16,
  },
  modal: {
    background: "#fff",
    borderRadius: 12,
    padding: 28,
    width: "100%",
    maxWidth: 400,
    boxShadow: "0 16px 48px rgba(15, 23, 42, 0.12)",
  },
  modalTitle: {
    margin: "0 0 20px",
    fontSize: 18,
    fontWeight: 600,
    color: "#0F172A",
  },
  field: { marginBottom: 16 },
  label: {
    display: "block",
    fontSize: 13,
    fontWeight: 500,
    color: "#334155",
    marginBottom: 6,
  },
  input: {
    width: "100%",
    padding: "10px 12px",
    fontSize: 14,
    border: "1px solid #E2E8F0",
    borderRadius: 8,
    boxSizing: "border-box",
  },
  errorBox: {
    marginBottom: 16,
    padding: "12px 14px",
    fontSize: 13,
    borderRadius: 8,
    background: "#FEF2F2",
    color: "#DC2626",
  },
  modalActions: {
    display: "flex",
    gap: 10,
    justifyContent: "flex-end",
    marginTop: 8,
  },
};
 
export default styles;