const styles = {
  page: {
    padding: '8px 4px 32px',
    fontFamily: "'DM Sans', 'Segoe UI', sans-serif",
  },
  loading: {
    padding: 48,
    textAlign: 'center',
    color: '#64748B',
  },
  header: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 24,
    flexWrap: 'wrap',
    gap: 16,
  },
  title: {
    margin: 0,
    fontSize: 26,
    fontWeight: 700,
    color: '#0F172A',
  },
  subtitle: {
    margin: '6px 0 0',
    fontSize: 14,
    color: '#64748B',
  },
  btnPrimary: {
    padding: '10px 18px',
    fontSize: 14,
    fontWeight: 600,
    color: '#fff',
    background: '#3B82F6',
    border: 'none',
    borderRadius: 8,
    cursor: 'pointer',
  },
  btnSecondary: {
    padding: '10px 16px',
    fontSize: 14,
    fontWeight: 500,
    color: '#64748B',
    background: '#fff',
    border: '1px solid #E2E8F0',
    borderRadius: 8,
    cursor: 'pointer',
  },
  toast: {
    marginBottom: 16,
    padding: '12px 14px',
    fontSize: 14,
    borderRadius: 8,
    background: '#ECFDF5',
    color: '#047857',
    border: '1px solid #A7F3D0',
  },
  statsRow: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))',
    gap: 16,
    marginBottom: 28,
  },
  statCard: {
    background: '#fff',
    border: '1px solid #E2E8F0',
    borderRadius: 12,
    padding: '20px 24px',
    boxShadow: '0 1px 3px rgba(0,0,0,0.04)',
  },
  statLabel: {
    margin: 0,
    fontSize: 13,
    color: '#64748B',
    fontWeight: 500,
  },
  statValue: {
    margin: '8px 0 0',
    fontSize: 32,
    fontWeight: 700,
    color: '#0F172A',
  },
  section: {
    marginBottom: 32,
  },
  sectionTitle: {
    margin: '0 0 12px',
    fontSize: 16,
    fontWeight: 600,
    color: '#0F172A',
  },
  tableWrap: {
    background: '#fff',
    borderRadius: 12,
    overflow: 'hidden',
    border: '1px solid #F1F5F9',
    boxShadow: '0 1px 3px rgba(0,0,0,0.06)',
  },
  table: {
    width: '100%',
    borderCollapse: 'collapse',
  },
  th: {
    padding: '11px 16px',
    textAlign: 'left',
    fontSize: 11,
    fontWeight: 600,
    color: '#94A3B8',
    textTransform: 'uppercase',
    letterSpacing: '0.05em',
    background: '#F8F9FB',
    borderBottom: '1px solid #F1F5F9',
  },
  tr: {
    borderBottom: '1px solid #F8F9FB',
  },
  td: {
    padding: '12px 16px',
    fontSize: 13,
    verticalAlign: 'middle',
  },
  memberCell: {
    display: 'flex',
    alignItems: 'center',
    gap: 10,
  },
  avatar: {
    width: 36,
    height: 36,
    borderRadius: '50%',
    background: '#3B82F6',
    color: '#fff',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: 13,
    fontWeight: 600,
    flexShrink: 0,
  },
  memberName: {
    fontSize: 13,
    fontWeight: 600,
    color: '#0F172A',
  },
  email: {
    fontSize: 13,
    color: '#3B82F6',
  },
  muted: {
    fontSize: 13,
    color: '#64748B',
  },
  badge: {
    display: 'inline-block',
    fontSize: 11,
    padding: '3px 10px',
    borderRadius: 99,
    fontWeight: 600,
  },
  empty: {
    padding: 40,
    textAlign: 'center',
    color: '#94A3B8',
    fontSize: 14,
  },
  toolbar: {
    display: 'flex',
    gap: 10,
    marginBottom: 12,
    alignItems: 'center',
  },
  searchWrap: {
    position: 'relative',
    flex: 1,
    minWidth: 220,
    maxWidth: 360,
  },
  searchIcon: {
    position: 'absolute',
    left: 10,
    top: '50%',
    transform: 'translateY(-50%)',
    width: 16,
    height: 16,
    pointerEvents: 'none',
  },
  searchInput: {
    width: '100%',
    padding: '8px 12px 8px 34px',
    fontSize: 13,
    border: '1px solid #E2E8F0',
    borderRadius: 8,
    background: '#fff',
    color: '#0F172A',
    outline: 'none',
    boxSizing: 'border-box',
  },
  deleteBtn: {
    padding: '5px 10px',
    fontSize: 12,
    fontWeight: 500,
    background: '#FEE2E2',
    color: '#DC2626',
    border: '1px solid #FECACA',
    borderRadius: 6,
    cursor: 'pointer',
  },
  actionCell: {
    textAlign: 'right',
  },
  overlay: {
    position: 'fixed',
    inset: 0,
    background: 'rgba(15, 23, 42, 0.4)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 1000,
    padding: 16,
  },
  modal: {
    background: '#fff',
    borderRadius: 12,
    padding: 28,
    width: '100%',
    maxWidth: 420,
    boxShadow: '0 16px 48px rgba(15, 23, 42, 0.12)',
  },
  field: { marginBottom: 16 },
  label: {
    display: 'block',
    fontSize: 13,
    fontWeight: 500,
    color: '#334155',
    marginBottom: 6,
  },
  input: {
    width: '100%',
    padding: '10px 12px',
    fontSize: 14,
    border: '1px solid #E2E8F0',
    borderRadius: 8,
    boxSizing: 'border-box',
  },
  errorBox: {
    marginBottom: 16,
    padding: '12px 14px',
    fontSize: 13,
    borderRadius: 8,
    background: '#FEF2F2',
    color: '#DC2626',
  },
  modalActions: {
    display: 'flex',
    gap: 10,
    justifyContent: 'flex-end',
    marginTop: 8,
  },
};

export default styles;
